// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using SIMA_SOFTWARE.Data;

#nullable disable

namespace SIMA_SOFTWARE.Migrations
{
    [DbContext(typeof(SimaDbContext))]
    partial class SimaDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.25")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("SIMA_Software.Models.Cliente", b =>
                {
                    b.Property<int>("IdCliente")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdCliente"));

                    b.Property<int?>("CuentaIdCuenta")
                        .HasColumnType("int");

                    b.Property<int?>("DireccionIdDireccion")
                        .HasColumnType("int");

                    b.Property<string>("Email")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<int>("IdCuenta")
                        .HasColumnType("int");

                    b.Property<int>("IdDireccion")
                        .HasColumnType("int");

                    b.Property<int>("IdTipoCliente")
                        .HasColumnType("int");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("Telefono")
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<int?>("TipoClienteIdTipoCliente")
                        .HasColumnType("int");

                    b.HasKey("IdCliente");

                    b.HasIndex("CuentaIdCuenta");

                    b.HasIndex("DireccionIdDireccion");

                    b.HasIndex("TipoClienteIdTipoCliente");

                    b.ToTable("Clientes");
                });

            modelBuilder.Entity("SIMA_Software.Models.Cuenta", b =>
                {
                    b.Property<int>("IdCuenta")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdCuenta"));

                    b.Property<string>("CondicionesPago")
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal>("Saldo")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)");

                    b.HasKey("IdCuenta");

                    b.ToTable("Cuentas");
                });

            modelBuilder.Entity("SIMA_Software.Models.DetalleFactura", b =>
                {
                    b.Property<int>("IdDetalleFactura")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdDetalleFactura"));

                    b.Property<int?>("DetalleProductoIdDetalleProducto")
                        .HasColumnType("int");

                    b.Property<int?>("FacturaIdFactura")
                        .HasColumnType("int");

                    b.Property<int>("IdDetalleProducto")
                        .HasColumnType("int");

                    b.Property<int>("IdFactura")
                        .HasColumnType("int");

                    b.HasKey("IdDetalleFactura");

                    b.HasIndex("DetalleProductoIdDetalleProducto");

                    b.HasIndex("FacturaIdFactura");

                    b.ToTable("DetalleFacturas");
                });

            modelBuilder.Entity("SIMA_Software.Models.DetalleProducto", b =>
                {
                    b.Property<int>("IdDetalleProducto")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdDetalleProducto"));

                    b.Property<int>("Cantidad")
                        .HasColumnType("int");

                    b.Property<decimal>("Descuento")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)");

                    b.Property<int>("IdProducto")
                        .HasColumnType("int");

                    b.Property<decimal>("PrecioUnitario")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)");

                    b.Property<int?>("ProductoIdProducto")
                        .HasColumnType("int");

                    b.HasKey("IdDetalleProducto");

                    b.HasIndex("ProductoIdProducto");

                    b.ToTable("DetalleProductos");
                });

            modelBuilder.Entity("SIMA_Software.Models.Direccion", b =>
                {
                    b.Property<int>("IdDireccion")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdDireccion"));

                    b.Property<string>("Barrio")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Calle")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("NroPuerta")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("IdDireccion");

                    b.ToTable("Direcciones");
                });

            modelBuilder.Entity("SIMA_Software.Models.Envio", b =>
                {
                    b.Property<int>("IdEnvio")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdEnvio"));

                    b.Property<int?>("EstadoIdEstado")
                        .HasColumnType("int");

                    b.Property<DateTime>("Fecha")
                        .HasColumnType("datetime2");

                    b.Property<int>("IdEstado")
                        .HasColumnType("int");

                    b.Property<int>("IdPedido")
                        .HasColumnType("int");

                    b.Property<int?>("PedidoIdPedido")
                        .HasColumnType("int");

                    b.HasKey("IdEnvio");

                    b.HasIndex("EstadoIdEstado");

                    b.HasIndex("PedidoIdPedido");

                    b.ToTable("Envios");
                });

            modelBuilder.Entity("SIMA_Software.Models.Estado", b =>
                {
                    b.Property<int>("IdEstado")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdEstado"));

                    b.Property<string>("Descripcion")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("IdEstado");

                    b.ToTable("Estados");
                });

            modelBuilder.Entity("SIMA_Software.Models.Factura", b =>
                {
                    b.Property<int>("IdFactura")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdFactura"));

                    b.Property<int?>("ClienteIdCliente")
                        .HasColumnType("int");

                    b.Property<DateTime>("FechaEmision")
                        .HasColumnType("datetime2");

                    b.Property<int>("IdCliente")
                        .HasColumnType("int");

                    b.Property<int>("IdPedido")
                        .HasColumnType("int");

                    b.Property<decimal>("Impuestos")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("MontoTotal")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)");

                    b.Property<int?>("PedidoIdPedido")
                        .HasColumnType("int");

                    b.HasKey("IdFactura");

                    b.HasIndex("ClienteIdCliente");

                    b.HasIndex("PedidoIdPedido");

                    b.ToTable("Facturas");
                });

            modelBuilder.Entity("SIMA_Software.Models.Inventario", b =>
                {
                    b.Property<int>("IdInventario")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdInventario"));

                    b.Property<int>("IdProducto")
                        .HasColumnType("int");

                    b.Property<int?>("ProductoIdProducto")
                        .HasColumnType("int");

                    b.Property<int>("Stock")
                        .HasColumnType("int");

                    b.HasKey("IdInventario");

                    b.HasIndex("ProductoIdProducto");

                    b.ToTable("Inventarios");
                });

            modelBuilder.Entity("SIMA_Software.Models.Notificacion", b =>
                {
                    b.Property<int>("IdNotificacion")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdNotificacion"));

                    b.Property<int?>("ClienteIdCliente")
                        .HasColumnType("int");

                    b.Property<int>("IdCliente")
                        .HasColumnType("int");

                    b.Property<int>("IdPedido")
                        .HasColumnType("int");

                    b.Property<string>("Mensaje")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("PedidoIdPedido")
                        .HasColumnType("int");

                    b.HasKey("IdNotificacion");

                    b.HasIndex("ClienteIdCliente");

                    b.HasIndex("PedidoIdPedido");

                    b.ToTable("Notificaciones");
                });

            modelBuilder.Entity("SIMA_Software.Models.Pedido", b =>
                {
                    b.Property<int>("IdPedido")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdPedido"));

                    b.Property<int?>("ClienteIdCliente")
                        .HasColumnType("int");

                    b.Property<DateTime>("Fecha")
                        .HasColumnType("datetime2");

                    b.Property<int>("IdCliente")
                        .HasColumnType("int");

                    b.HasKey("IdPedido");

                    b.HasIndex("ClienteIdCliente");

                    b.ToTable("Pedidos");
                });

            modelBuilder.Entity("SIMA_Software.Models.PedidoProducto", b =>
                {
                    b.Property<int>("IdPedidoProducto")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdPedidoProducto"));

                    b.Property<int>("Cantidad")
                        .HasColumnType("int");

                    b.Property<decimal>("Descuento")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)");

                    b.Property<int>("IdPedido")
                        .HasColumnType("int");

                    b.Property<int>("IdProducto")
                        .HasColumnType("int");

                    b.Property<int?>("PedidoIdPedido")
                        .HasColumnType("int");

                    b.Property<decimal>("PrecioUnitario")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)");

                    b.Property<int?>("ProductoIdProducto")
                        .HasColumnType("int");

                    b.HasKey("IdPedidoProducto");

                    b.HasIndex("PedidoIdPedido");

                    b.HasIndex("ProductoIdProducto");

                    b.ToTable("PedidoProductos");
                });

            modelBuilder.Entity("SIMA_Software.Models.Producto", b =>
                {
                    b.Property<int>("IdProducto")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdProducto"));

                    b.Property<string>("Nombre")
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal>("Precio")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)");

                    b.HasKey("IdProducto");

                    b.ToTable("Productos");
                });

            modelBuilder.Entity("SIMA_Software.Models.Stock", b =>
                {
                    b.Property<int>("IdStock")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdStock"));

                    b.Property<int>("Cantidad")
                        .HasColumnType("int");

                    b.Property<DateTime>("FechaActualizacion")
                        .HasColumnType("datetime2");

                    b.Property<int>("IdInventario")
                        .HasColumnType("int");

                    b.Property<int?>("InventarioIdInventario")
                        .HasColumnType("int");

                    b.Property<decimal>("PrecioUnitario")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)");

                    b.HasKey("IdStock");

                    b.HasIndex("InventarioIdInventario");

                    b.ToTable("Stocks");
                });

            modelBuilder.Entity("SIMA_Software.Models.TipoCliente", b =>
                {
                    b.Property<int>("IdTipoCliente")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdTipoCliente"));

                    b.Property<string>("Categoria")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("IdTipoCliente");

                    b.ToTable("TipoClientes");
                });

            modelBuilder.Entity("SIMA_Software.Models.Cliente", b =>
                {
                    b.HasOne("SIMA_Software.Models.Cuenta", "Cuenta")
                        .WithMany("Clientes")
                        .HasForeignKey("CuentaIdCuenta");

                    b.HasOne("SIMA_Software.Models.Direccion", "Direccion")
                        .WithMany("Clientes")
                        .HasForeignKey("DireccionIdDireccion");

                    b.HasOne("SIMA_Software.Models.TipoCliente", "TipoCliente")
                        .WithMany("Clientes")
                        .HasForeignKey("TipoClienteIdTipoCliente");

                    b.Navigation("Cuenta");

                    b.Navigation("Direccion");

                    b.Navigation("TipoCliente");
                });

            modelBuilder.Entity("SIMA_Software.Models.DetalleFactura", b =>
                {
                    b.HasOne("SIMA_Software.Models.DetalleProducto", "DetalleProducto")
                        .WithMany("DetallesFactura")
                        .HasForeignKey("DetalleProductoIdDetalleProducto");

                    b.HasOne("SIMA_Software.Models.Factura", "Factura")
                        .WithMany("DetallesFactura")
                        .HasForeignKey("FacturaIdFactura");

                    b.Navigation("DetalleProducto");

                    b.Navigation("Factura");
                });

            modelBuilder.Entity("SIMA_Software.Models.DetalleProducto", b =>
                {
                    b.HasOne("SIMA_Software.Models.Producto", "Producto")
                        .WithMany("DetallesProducto")
                        .HasForeignKey("ProductoIdProducto");

                    b.Navigation("Producto");
                });

            modelBuilder.Entity("SIMA_Software.Models.Envio", b =>
                {
                    b.HasOne("SIMA_Software.Models.Estado", "Estado")
                        .WithMany("Envios")
                        .HasForeignKey("EstadoIdEstado");

                    b.HasOne("SIMA_Software.Models.Pedido", "Pedido")
                        .WithMany("Envios")
                        .HasForeignKey("PedidoIdPedido");

                    b.Navigation("Estado");

                    b.Navigation("Pedido");
                });

            modelBuilder.Entity("SIMA_Software.Models.Factura", b =>
                {
                    b.HasOne("SIMA_Software.Models.Cliente", "Cliente")
                        .WithMany("Facturas")
                        .HasForeignKey("ClienteIdCliente");

                    b.HasOne("SIMA_Software.Models.Pedido", "Pedido")
                        .WithMany()
                        .HasForeignKey("PedidoIdPedido");

                    b.Navigation("Cliente");

                    b.Navigation("Pedido");
                });

            modelBuilder.Entity("SIMA_Software.Models.Inventario", b =>
                {
                    b.HasOne("SIMA_Software.Models.Producto", "Producto")
                        .WithMany("Inventarios")
                        .HasForeignKey("ProductoIdProducto");

                    b.Navigation("Producto");
                });

            modelBuilder.Entity("SIMA_Software.Models.Notificacion", b =>
                {
                    b.HasOne("SIMA_Software.Models.Cliente", "Cliente")
                        .WithMany()
                        .HasForeignKey("ClienteIdCliente");

                    b.HasOne("SIMA_Software.Models.Pedido", "Pedido")
                        .WithMany()
                        .HasForeignKey("PedidoIdPedido");

                    b.Navigation("Cliente");

                    b.Navigation("Pedido");
                });

            modelBuilder.Entity("SIMA_Software.Models.Pedido", b =>
                {
                    b.HasOne("SIMA_Software.Models.Cliente", "Cliente")
                        .WithMany("Pedidos")
                        .HasForeignKey("ClienteIdCliente");

                    b.Navigation("Cliente");
                });

            modelBuilder.Entity("SIMA_Software.Models.PedidoProducto", b =>
                {
                    b.HasOne("SIMA_Software.Models.Pedido", "Pedido")
                        .WithMany("PedidoProductos")
                        .HasForeignKey("PedidoIdPedido");

                    b.HasOne("SIMA_Software.Models.Producto", "Producto")
                        .WithMany("PedidoProductos")
                        .HasForeignKey("ProductoIdProducto");

                    b.Navigation("Pedido");

                    b.Navigation("Producto");
                });

            modelBuilder.Entity("SIMA_Software.Models.Stock", b =>
                {
                    b.HasOne("SIMA_Software.Models.Inventario", "Inventario")
                        .WithMany("Stocks")
                        .HasForeignKey("InventarioIdInventario");

                    b.Navigation("Inventario");
                });

            modelBuilder.Entity("SIMA_Software.Models.Cliente", b =>
                {
                    b.Navigation("Facturas");

                    b.Navigation("Pedidos");
                });

            modelBuilder.Entity("SIMA_Software.Models.Cuenta", b =>
                {
                    b.Navigation("Clientes");
                });

            modelBuilder.Entity("SIMA_Software.Models.DetalleProducto", b =>
                {
                    b.Navigation("DetallesFactura");
                });

            modelBuilder.Entity("SIMA_Software.Models.Direccion", b =>
                {
                    b.Navigation("Clientes");
                });

            modelBuilder.Entity("SIMA_Software.Models.Estado", b =>
                {
                    b.Navigation("Envios");
                });

            modelBuilder.Entity("SIMA_Software.Models.Factura", b =>
                {
                    b.Navigation("DetallesFactura");
                });

            modelBuilder.Entity("SIMA_Software.Models.Inventario", b =>
                {
                    b.Navigation("Stocks");
                });

            modelBuilder.Entity("SIMA_Software.Models.Pedido", b =>
                {
                    b.Navigation("Envios");

                    b.Navigation("PedidoProductos");
                });

            modelBuilder.Entity("SIMA_Software.Models.Producto", b =>
                {
                    b.Navigation("DetallesProducto");

                    b.Navigation("Inventarios");

                    b.Navigation("PedidoProductos");
                });

            modelBuilder.Entity("SIMA_Software.Models.TipoCliente", b =>
                {
                    b.Navigation("Clientes");
                });
#pragma warning restore 612, 618
        }
    }
}
